config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :vinyls do
    resources :bookings, except: [ :index, :show, :destroy, :edit, :update]
    resources :reviews, only: [ :new, :create]
    resources :tracks, only: [ :new, :create]
  end
  resources :bookings, only: [ :index, :destroy, :edit, :update] do
    resources :reviews, only: [ :new, :create, :edit, :update]
  end

  resources :artists, only: [ :new, :create]

end

app/views/shared/_artist_form.html.erb
  <%= simple_form_for @artist do |f| %>
    <%= f.input :name, label:'Artist Name', placeholder: 'Pink Floyd' %>
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright ">
     <i class="fas fa-headphones-alt"></i> Techno Tools - Let your heart beat for music. <i class="fas fa-music"></i>
  </div>
  <div class="GDPR-links d-flex">
    <div> <a href="#">Conditions</a> </div>
    <div> <a href="#">Politique de confidentialité</a> </div>
    <div> <a href="#">Plan du site</a> </div>
    <div> <a href="#">Fonctionnement du site</a> </div>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_modal_add_track.html.erb
<div class="modal fade" id="addTrack" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="form-wrapper" id="booking-modal-form">
            <%= simple_form_for [@vinyl, @track] do |f| %>
              <%= f.input :name , label: 'Track Title' %>
              <%= f.input :url , label: 'Insert Youtube url' %>
              <div class="modal-footer">
                <%= f.button :submit, "Add Track", class: "btn btn-primary" %>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_booking.html.erb
<div class="modal fade" id="bookingModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="form-wrapper" id="booking-modal-form">
            <%= simple_form_for [vinyl, booking] do |f| %>
              <%= f.input :start_rent, label: "Select dates:", as: :string, required: false, input_html: { id: "range_start", class: "d-none"} %>
              <%= f.input :end_rent, label: false, as: :string, required: false, input_html: { id: "range_end", class: "d-none" } %>
              <div class="modal-footer">
                <%= f.button :submit, "Book", class: "btn btn-primary" %>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_reviews.html.erb
<div class="modal fade" id="allReviewsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Reviews</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <button class="btn btn-dark w-100 mb-4" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Click to leave a comment
        </button>
      </div>
      <div class="collapse" id="collapseExample">
        <div class="card card-body">
          <%= simple_form_for [ @vinyl, @review ] do |f| %>
            <%= f.input :comment %>
            <%= f.input :rating %>
            <%= f.submit class: 'btn btn-dark w-100'%>
          <% end %>
        </div>
      </div>
      <% @vinyl.reviews.reverse.each do |review| %>
        <div class="review-card">
          <img src="https://geo-static.traxsource.com/files/artists/10554.jpg" />
          <div class="review-card-infos">
            <h4><%= review.booking.user.pseudo %> </h4>
            <repeat n='<%= review.rating %>'></repeat>
            <p><%= review.comment %></p>
            <p><%= review.created_at.strftime('%d %B %Y') %></p>
          </div>
        </div>
      <% end %>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://cdn.shopify.com/s/files/1/1816/1199/products/MBTA_Logo_2.5_Circle_Magnet_WEB_grande.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-link"><%= link_to 'Home', root_path, class: "link-without-style"%></li>
      <%if  current_user %>
        <li class="nav-link"><%= link_to 'Orders & Bookings', bookings_path, class: "link-without-style" %></li>
        <li class="nav-link"><%= link_to 'Post New Vinyl', new_vinyl_path, class: "link-without-style" %></li>
      <% end %>
      <%if  current_user == nil %>
        <li class="nav-link"><%= link_to "Connexion", new_user_session_path, class: "link-without-style" %></li>
        <li class="nav-link"><%= link_to "Sign-up", new_user_registration_path, class: "link-without-style" %></li>
      <% end %>

      <%if  current_user %>
      <li class="nav-item dropdown">
          <%= image_tag "https://geo-static.traxsource.com/files/artists/10554.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Orders & Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log-out", destroy_user_session_path, method: :delete , class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_record-image.html.erb
<div class="container records d-flex mb-5">

  <div>
    <div class="record">
      <%= image_tag "https://res.cloudinary.com/de8kltuyf/image/upload/v1581952923/Technotools/Beattles.jpg", class: 'record-image' %>
    </div>
    <div class="record_infos">
      <h3>The Beatles</h3>
      <h5>Abbey Road</h5>
    </div>
  </div>

  <div>
    <div class="record">
      <%= image_tag "https://res.cloudinary.com/de8kltuyf/image/upload/v1581952923/Technotools/Pink%20Floyd.jpg", class: 'record-image' %>
    </div>
    <div class="record_infos">
      <h3>The Pink Floyd </h3>
      <h5>Dark Side of the Moon</h5>
    </div>
  </div>

  <div>
    <div class="record">
      <%= image_tag "https://res.cloudinary.com/de8kltuyf/image/upload/v1581952923/Technotools/The%20dooors.jpg", class: 'record-image' %>
    </div>
    <div class="record_infos">
      <h3>The Doors</h3>
      <h5>L.A Woman</h5>
    </div>
  </div>
</div>

app/views/shared/_record_image.html.erb
<div>
  <div class="record">
    <%= cl_image_tag vinyl.photo.key, height: 200, width: 200, crop: :fill, class: 'record-image'%>
  </div>
  <div class="record_infos">
    <h3><%= vinyl.name %></h3>
    <h5><%= vinyl.artist.name %></h5>
  </div>
</div>

app/views/shared/_record_image_booking.html.erb
<div>
  <%= link_to vinyl_path(vinyl), class: "link-without-style" do  %>
    <div class="record">
      <%= cl_image_tag vinyl.photo.key, height: 200, width: 200, crop: :fill, class: 'record-image'%>
    </div>
    <div class="record_infos">
      <h3><%= vinyl.name %></h3>
      <h5><%= vinyl.artist.name %></h5>
      <%= link_to "EDIT", edit_vinyl_path(vinyl), class: "btn btn-secondary btn-block " %>
      <br>
      <%= link_to "DELETE", vinyl_path(vinyl), method: :delete, data: { confirm: "Sure ?" }, class: "btn btn-dark btn-block " %>
    </div>
  <% end %>
</div>

app/views/shared/_search-bar.html.erb
<!-- <div class="container search mt-5">
  <form action="/vinyls" method="get" class="d-flex justify-content-between  align-items-center">
    <input  type="text"   class="border-dark shadow-lg rounded-pill p-4" placeholder="Where?">
    <input  type="text"   class="border-dark shadow-lg rounded-pill p-4" placeholder="From?">
    <input  type="text"   class="border-dark shadow-lg rounded-pill p-4" placeholder="To?">
    <button type="submit" class="border-dark shadow-lg rounded-pill bg-transparent font-weight-bolder btn btn-light p-4"> Find a Vinyl</button>
  </form>
</div> -->

<%= form_tag vinyls_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "border-dark shadow-lg rounded-pill p-4",
    placeholder: "Where?"
  %>
  <%= submit_tag "Find a vinyl", class: "border-dark shadow-lg rounded-pill bg-transparent font-weight-bolder btn btn-light p-4" %>
<% end %>

app/views/shared/_search_bar.html.erb
<div class="container search d-flex align-items-center">
    <%= simple_form_for :search, method: "get", url: vinyls_path do |f| %>
        <div class="d-flex justify-content-center">
          <%= f.input :query, as: :string, required: false, input_html: {class: "border-dark shadow-lg rounded-pill py-4"}, placeholder: "Looking for something?", label: false %>
          <%= f.button :submit, "Find a vinyl", class: "border-dark shadow-lg rounded-pill bg-white font-weight-bolder btn btn-light btn-lg mb-5 ml-2" %>
        </div>
    <% end %>
</div>

app/views/shared/_spinning-record.html.erb
<div class="spinning-logo">
  <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     width="226px" height="226px" viewBox="0 0 226 226" enable-background="new 0 0 226 226" xml:space="preserve">
  <g id="record">
    <circle fill="#2C3E50" cx="112.11" cy="121.222" r="88.333"/>
    <circle fill="#E74C3C" cx="112.109" cy="121.223" r="35.333"/>
    <path fill="#4F5E6D" d="M89.414,168.208c-18.393-9.132-29.818-27.552-29.816-48.073c-0.001-10.566,3.068-20.789,8.875-29.563
      l4.17,2.76c-5.264,7.953-8.046,17.222-8.045,26.803c-0.001,18.609,10.36,35.313,27.04,43.594L89.414,168.208z"/>
    <circle fill="#FFFFFF" cx="111.664" cy="121.333" r="12.333"/>
    <path fill="#4F5E6D" d="M84.985,177.39c-21.99-10.919-35.651-32.943-35.65-57.478c0-12.675,3.692-24.932,10.68-35.448l4.164,2.768
      c-6.44,9.692-9.845,20.993-9.844,32.68c0,22.623,12.596,42.931,32.874,53L84.985,177.39z"/>
    <path fill="#4F5E6D" d="M79.668,188.412c-26.311-13.062-42.655-39.413-42.654-68.768c-0.001-15.61,4.659-30.633,13.477-43.446
      l4.119,2.835c-8.241,11.975-12.597,26.018-12.596,40.611c-0.001,27.444,15.279,52.078,39.877,64.29L79.668,188.412z"/>
    <path fill="#4F5E6D" d="M153.016,155.227l-3.962-3.051c11.361-14.755,13.352-34.311,5.193-51.035
      c-4.2-8.613-10.764-15.724-18.981-20.564l2.538-4.308c9.065,5.34,16.305,13.183,20.937,22.68
      C167.737,117.392,165.543,138.956,153.016,155.227z"/>
    <path fill="#4F5E6D" d="M161.021,161.537l-3.962-3.051c13.812-17.939,16.23-41.714,6.313-62.046
      c-5.123-10.504-13.136-19.169-23.174-25.058l2.53-4.312c10.89,6.389,19.583,15.787,25.138,27.179
      C178.623,116.299,175.999,142.083,161.021,161.537z"/>
    <path fill="#4F5E6D" d="M170.632,169.113l-3.962-3.051c16.755-21.76,19.69-50.599,7.659-75.263
      c-6.396-13.118-16.467-23.83-29.124-30.98l2.459-4.354c13.542,7.65,24.317,19.11,31.159,33.142
      C191.692,114.99,188.554,145.838,170.632,169.113z"/>
  </g>
  <g id="needle">
    <circle fill="#9B8010" cx="191.664" cy="26.333" r="18.333"/>
    <path fill="#FFFFFF" d="M195.152,38.158c5.111-1.505,8.845-6.226,8.845-11.825c0-6.811-5.521-12.333-12.333-12.333
      c-6.811,0-12.333,5.521-12.333,12.333c0,3.628,1.576,6.88,4.07,9.137l-11.944,91.183c-1.618-0.176-3.246,0.638-4.014,2.18
      l-12.033,24.169c-0.985,1.979-0.18,4.379,1.797,5.364l9.847,4.901c1.977,0.986,4.379,0.181,5.363-1.797l5.317-10.681l4.804,2.73
      l1.482-2.607l-4.948-2.812l5.378-10.801c0.962-1.932,0.207-4.261-1.675-5.285c0.083-0.244,0.145-0.499,0.179-0.764L195.152,38.158z
      "/>
  </g>
  </svg>
</div>

app/views/shared/_spinning_record.html.erb
<div class="spinning-logo">
  <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     width="226px" height="226px" viewBox="0 0 226 226" enable-background="new 0 0 226 226" xml:space="preserve">
  <g id="record">
    <circle fill="#2C3E50" cx="112.11" cy="121.222" r="88.333"/>
    <circle fill="#E74C3C" cx="112.109" cy="121.223" r="35.333"/>
    <path fill="#4F5E6D" d="M89.414,168.208c-18.393-9.132-29.818-27.552-29.816-48.073c-0.001-10.566,3.068-20.789,8.875-29.563
      l4.17,2.76c-5.264,7.953-8.046,17.222-8.045,26.803c-0.001,18.609,10.36,35.313,27.04,43.594L89.414,168.208z"/>
    <circle fill="#FFFFFF" cx="111.664" cy="121.333" r="12.333"/>
    <path fill="#4F5E6D" d="M84.985,177.39c-21.99-10.919-35.651-32.943-35.65-57.478c0-12.675,3.692-24.932,10.68-35.448l4.164,2.768
      c-6.44,9.692-9.845,20.993-9.844,32.68c0,22.623,12.596,42.931,32.874,53L84.985,177.39z"/>
    <path fill="#4F5E6D" d="M79.668,188.412c-26.311-13.062-42.655-39.413-42.654-68.768c-0.001-15.61,4.659-30.633,13.477-43.446
      l4.119,2.835c-8.241,11.975-12.597,26.018-12.596,40.611c-0.001,27.444,15.279,52.078,39.877,64.29L79.668,188.412z"/>
    <path fill="#4F5E6D" d="M153.016,155.227l-3.962-3.051c11.361-14.755,13.352-34.311,5.193-51.035
      c-4.2-8.613-10.764-15.724-18.981-20.564l2.538-4.308c9.065,5.34,16.305,13.183,20.937,22.68
      C167.737,117.392,165.543,138.956,153.016,155.227z"/>
    <path fill="#4F5E6D" d="M161.021,161.537l-3.962-3.051c13.812-17.939,16.23-41.714,6.313-62.046
      c-5.123-10.504-13.136-19.169-23.174-25.058l2.53-4.312c10.89,6.389,19.583,15.787,25.138,27.179
      C178.623,116.299,175.999,142.083,161.021,161.537z"/>
    <path fill="#4F5E6D" d="M170.632,169.113l-3.962-3.051c16.755-21.76,19.69-50.599,7.659-75.263
      c-6.396-13.118-16.467-23.83-29.124-30.98l2.459-4.354c13.542,7.65,24.317,19.11,31.159,33.142
      C191.692,114.99,188.554,145.838,170.632,169.113z"/>
  </g>
  <g id="needle">
    <circle fill="#9B8010" cx="191.664" cy="26.333" r="18.333"/>
    <path fill="#FFFFFF" d="M195.152,38.158c5.111-1.505,8.845-6.226,8.845-11.825c0-6.811-5.521-12.333-12.333-12.333
      c-6.811,0-12.333,5.521-12.333,12.333c0,3.628,1.576,6.88,4.07,9.137l-11.944,91.183c-1.618-0.176-3.246,0.638-4.014,2.18
      l-12.033,24.169c-0.985,1.979-0.18,4.379,1.797,5.364l9.847,4.901c1.977,0.986,4.379,0.181,5.363-1.797l5.317-10.681l4.804,2.73
      l1.482-2.607l-4.948-2.812l5.378-10.801c0.962-1.932,0.207-4.261-1.675-5.285c0.083-0.244,0.145-0.499,0.179-0.764L195.152,38.158z
      "/>
  </g>
  </svg>
</div>